import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
import './globals.css'

const inter = Inter({subsets:['latin']})

export const metadata = {
  title: 'Create next app',
  description: 'Generated by created next app'
}

export default function RootLayout({children}: {children: ReactNode}){
  return
}